### ISSUE TITLE
Wrong reply made by the bot on discord (replied from telegram to the telebridge bot)

### ISSUE THREAD

**Issue by BGamerManu** [TeleBridge/TeleBridge#7]
## Problem description
The discord bot counted as a reply to one of my messages a reply that was originally not intended for me but another user

## Screenshots

| Explanation | Screenshot |
| :---: | :---: |
| What the bot made (In the first message, it sent a silenced reply. And in the second message it sent a "sounded" notification) | ![Screen 1](https://github.com/TeleBridge/TeleBridge/assets/63466244/da42a9b7-e2ed-40b3-b960-ebe4314411ed)
| What i actually made (Replying to the user and not to myself) | ![Screen 2](https://github.com/TeleBridge/TeleBridge/assets/63466244/ef5c6b3c-e5d1-4277-aa56-2928a77df6e6)

**Comment by AntogamerYT** [comment]
Looks like a strange scenario, i tried replicating this but i still got the right reply

![image](https://github.com/TeleBridge/TeleBridge/assets/64664639/a3ce3299-bd7b-42fc-8242-c94dec64fa42)
![image](https://github.com/TeleBridge/TeleBridge/assets/64664639/73c14565-c5ff-44f4-8725-b4b8f65f5fc5)

E' un caso strano perchè replicandolo sono riuscito ad avere una risposta, se hai qualcos'altro da dire scrivi (possibilmente in inglese)

**Comment by AntogamerYT** [comment]
Fixed
